{% set version = "0.12.2" %}

package:
  name: gwpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gwpy/gwpy-{{ version }}.tar.gz
  sha256: 74c5066e19e2b10dd0571ac0f0bd588b302d1f6de639a994021a580bb90d93f4

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python >=2.7
    - six >=1.5
    - python-dateutil
    - enum34  # [py2k]
    - numpy >=1.7.1
    - scipy >=0.12.1
    - matplotlib >=1.2.0,!=2.1.0,!=2.1.1
    - astropy >=1.1.1
    - h5py >=1.3
    - ligo-segments >=1.0.0
    - tqdm >=4.10.0
    - ligotimegps >=1.2.1

test:
  requires:
    - pytest >=3.1,!=3.8.0
    - freezegun >=0.2.3
    - sqlparse >=0.2.0
    - beautifulsoup4
    - mock  # [py2k]
  imports:
    - gwpy
    - gwpy.astro
    - gwpy.cli
    - gwpy.detector
    - gwpy.frequencyseries
    - gwpy.io
    - gwpy.plot
    - gwpy.segments
    - gwpy.signal
    - gwpy.spectrogram
    - gwpy.table
    - gwpy.tests
    - gwpy.time
    - gwpy.timeseries
    - gwpy.types
    - gwpy.utils
  commands:
    - python -m pytest --pyargs gwpy
    - gwpy-plot --help

about:
  home: https://gwpy.github.io
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: A python package for gravitational-wave astrophysics
  description: |
    GWpy is a collaboration-driven Python package providing tools for
    studying data from ground-based gravitational-wave detectors.

    GWpy provides a user-friendly, intuitive interface to the common
    time-domain and frequency-domain data produced by the LIGO and Virgo
    observatories and their analyses, with easy-to-follow tutorials at each
    step.

extra:
  recipe-maintainers:
    - duncanmmacleod
