{% set name = "gwpy" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2ffbf43cbc9c25160193285af646c6ac53a809eb7a1613859502bcd0dff9ef9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - gwpy-plot = gwpy.cli.gwpy_plot:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=38.2.5
    - setuptools-scm
  run:
    - astropy >=3.0.0
    - dqsegdb2
    - gwdatafind
    - gwosc >=0.5.3
    - h5py >=2.7.0
    - ligo-segments >=1.0.0
    - ligotimegps >=1.2.1
    - matplotlib-base >=3.3.0
    - numpy >=1.15.0
    - python >=3.6
    - python-dateutil
    - scipy >=1.2.0
    - tqdm >=4.10.0

test:
  requires:
    - beautifulsoup4
    - freezegun >=0.3.12
    - pip
    - pytest >=3.9.1
    - python-framel
    - python-lal
    - python-ldas-tools-framecpp
    - python-ligo-lw
    - uproot
  commands:
    # check requirements
    - python -m pip check
    # run test suite
    - python -m pytest --pyargs gwpy
    # check command-line interfaces
    - python -m gwpy.time --help
    - gwpy-plot --help

about:
  home: https://gwpy.github.io
  dev_url: https://github.com/gwpy/gwpy.git
  doc_url: https://gwpy.github.io/docs/{{ version }}/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A python package for gravitational-wave astrophysics
  description: |
    GWpy is a collaboration-driven Python package providing tools for
    studying data from ground-based gravitational-wave detectors.

    GWpy provides a user-friendly, intuitive interface to the common
    time-domain and frequency-domain data produced by the LIGO and Virgo
    observatories and their analyses, with easy-to-follow tutorials at each
    step.

extra:
  recipe-maintainers:
    - duncanmmacleod
