{% set name = "gwpy" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3f40c36218c9766b6ad96d8831f8e019344995ef92793445a476fdd9ff26bb6c
  patches:
    # fix name of event in GWOSC test
    - 4f70b209cfee46bcb9ecd4524931b227bc4e3d9b.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - gwpy-plot = gwpy.cli.gwpy_plot:main

requirements:
  host:
    - pip
    - python
    - setuptools >=20.2.2
  run:
    - astropy >=3.0.0
    - dqsegdb2
    - gwdatafind
    - gwosc >=0.5.3
    - h5py >=1.3
    - ligo-segments >=1.0.0
    - ligotimegps >=1.2.1
    - matplotlib-base >=3.1.0,<3.3.0a0
    - numpy >=1.12.0
    - python
    - python-dateutil
    - scipy >=1.2.0
    - tqdm >=4.10.0

test:
  requires:
    - beautifulsoup4
    - freezegun >=0.2.3
    - pytest >=3.3.0
  imports:
    - gwpy
    - gwpy.astro
    - gwpy.cli
    - gwpy.detector
    - gwpy.frequencyseries
    - gwpy.io
    - gwpy.plot
    - gwpy.segments
    - gwpy.signal
    - gwpy.spectrogram
    - gwpy.table
    - gwpy.testing
    - gwpy.time
    - gwpy.timeseries
    - gwpy.types
    - gwpy.utils
  commands:
    - python -m pytest --pyargs gwpy
    - python -m gwpy.time --help
    - gwpy-plot --help

about:
  home: https://gwpy.github.io
  dev_url: https://github.com/gwpy/gwpy/
  doc_url: https://gwpy.github.io/docs/stable/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A python package for gravitational-wave astrophysics
  description: |
    GWpy is a collaboration-driven Python package providing tools for
    studying data from ground-based gravitational-wave detectors.

    GWpy provides a user-friendly, intuitive interface to the common
    time-domain and frequency-domain data produced by the LIGO and Virgo
    observatories and their analyses, with easy-to-follow tutorials at each
    step.

extra:
  recipe-maintainers:
    - duncanmmacleod
