schema_version: 1

context:
  name: gwpy
  version: "4.0.1"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 477aa69bd40506bfb0df5ec779d9dd6fef562a3bfabe58a52b297e25c57f61f0

build:
  number: 0
  noarch: python
  python:
    entry_points:
      - gwpy-plot = gwpy.cli.gwpy_plot:main
  script: uv pip install --python ${{ PYTHON }} . --link-mode=copy --no-build-isolation --no-deps -v

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61
    - setuptools-scm >=3.4.3
    - uv
    - wheel
  run:
    - astropy-base >=6.1.6
    - dateparser >=1.2.0
    - dqsegdb2 >=1.3.0
    - gwdatafind >=2.0.0
    - gwosc >=0.6.0
    - h5py >=3.11.0
    - igwn-segments >=2.0.0
    - ligotimegps >=2.1.0
    - matplotlib-base >=3.8.0
    - numpy >=1.24.4
    - packaging >=24.2
    - python >=${{ python_min }}
    - python-dateutil >=2.9.0
    - requests >=2.32.3
    - scipy >=1.12.0
    - tqdm >=4.67.0

tests:
  - requirements:
      run:
        - arrakis-python >=0.2.0
        - beautifulsoup4
        - inspiral-range >=0.9.3
        - pip
        - pytest >=8.4
        - pytest-freezer >=0.4.9
        - pytest-requires >=0.1.0
        - python ${{ python_min }}.*
        - python-framel >=8.40.1
        - python-lal
        - python-lalframe
        - python-ldas-tools-framecpp
        - requests-mock >=1.12.1
        - uproot >=4.1.5
    script:
      # Check metadata
      - python -m pip check
      - python -m pip show gwpy
      # Run the test suite
      - python -m pytest -ra --pyargs gwpy
      # Test command-line entry points
      - python -m gwpy.time --help
      - gwpy-plot --help

about:
  summary: A python package for gravitational-wave astrophysics
  description: |
    GWpy is a collaboration-driven Python package providing tools for
    studying data from ground-based gravitational-wave detectors.

    GWpy provides a user-friendly, intuitive interface to the common
    time-domain and frequency-domain data produced by the LIGO and Virgo
    observatories and their analyses, with easy-to-follow tutorials at each
    step.
  homepage: https://gwpy.github.io
  repository: https://gitlab.com/gwpy/gwpy.git
  documentation: https://gwpy.github.io/docs/${{ version }}/
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - duncanmmacleod
