# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "d2iURz0NKlJhFlXNIWLKVs3xm8k16ZS3g/SDoCuZSApUD577QVWjtXAfVWvGUPsF/hJ3K6M9Zgjj33fxgzayAYUj6OdStH2GQ6Oe0oQ9x0nAN+pEQZuFE8f1YVqHncE9/HYQEavmnXOYrGM6I6Y5EcNZ9YQ3kQzdjuhbGLoc/F8J+HB1Nlsy1F6FFey0hG0/0oyELclN00qxS/k5jLkse9hayAWNBNCmnH8BeSOOy5UiAX0AfZErlm0hAhtSRKQHbBHWdTQtmnKcAQbZ7i9PDEJ/+BovHxe/giUhFUPdsMKvScF+ZUQIUhhZVuHIJQVLe6dfmBNx+V8iUiq9Hn/uGEPcphyuDM8kVU1zoScCHcepDXYbTCFwmjg+fAxceueLZmNPVCL5Uk6lR3vCz4pY5Io97NaKI9F9Jf8TqCHVQUcvqxe7XEO9O0SIvFi2jzL3HlTGRFYMRA9J2ZyF4/6Duhhbq7frYgRc/m/54H/AK2EGFcLAwOk1JG208J8Jr7cvN9TOydvhdcDjVHmk0cfChfbOQaRI7UgDfK7vx06XSfvhCq1Loh3SniQ2lxBO1JDRYHLzl+yZq8Qdop6Q/7bHT6oYp1bKWyCr/jUH1oPaOlFGxX49+0nHe1HIfoMQtwai3Le6ZfN74xtZ4ycmkVjCw+PnWcI4rCuK1s38eYBJrms="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
