travis:
  secure:
    BINSTAR_TOKEN: d2iURz0NKlJhFlXNIWLKVs3xm8k16ZS3g/SDoCuZSApUD577QVWjtXAfVWvGUPsF/hJ3K6M9Zgjj33fxgzayAYUj6OdStH2GQ6Oe0oQ9x0nAN+pEQZuFE8f1YVqHncE9/HYQEavmnXOYrGM6I6Y5EcNZ9YQ3kQzdjuhbGLoc/F8J+HB1Nlsy1F6FFey0hG0/0oyELclN00qxS/k5jLkse9hayAWNBNCmnH8BeSOOy5UiAX0AfZErlm0hAhtSRKQHbBHWdTQtmnKcAQbZ7i9PDEJ/+BovHxe/giUhFUPdsMKvScF+ZUQIUhhZVuHIJQVLe6dfmBNx+V8iUiq9Hn/uGEPcphyuDM8kVU1zoScCHcepDXYbTCFwmjg+fAxceueLZmNPVCL5Uk6lR3vCz4pY5Io97NaKI9F9Jf8TqCHVQUcvqxe7XEO9O0SIvFi2jzL3HlTGRFYMRA9J2ZyF4/6Duhhbq7frYgRc/m/54H/AK2EGFcLAwOk1JG208J8Jr7cvN9TOydvhdcDjVHmk0cfChfbOQaRI7UgDfK7vx06XSfvhCq1Loh3SniQ2lxBO1JDRYHLzl+yZq8Qdop6Q/7bHT6oYp1bKWyCr/jUH1oPaOlFGxX49+0nHe1HIfoMQtwai3Le6ZfN74xtZ4ycmkVjCw+PnWcI4rCuK1s38eYBJrms=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
