travis:
  secure:
    BINSTAR_TOKEN: oAXsMprkJDn455YIBNrN/wctVT214V0ORguZdszbWbHbQXDwVzuC9C5Et1YVl9qcU14M+fvoxheMpwqjJyuDCxBrp17gO0uY4whPyQ5WkMyvMWfUwk3ZyUkbvzRJrrq+V8fPtVkJ5r9wZTN/GrMf8WBJF8smDfG5wuAbUsQl6rw3YRHgiaqzyKVg+3N4PWzRra3DGcUJPG2UQqxywuegWe+nUG5uDm63WK+RC/MTKhbZgrEwDIijDytVz7/gMU5AiZfQzCQ5vO/gKwUh8fa0TQfPFmKkLSfhcmIePtkdzOkofIH/fvv6Q88WSeHfJ3T9D8wvpk254VUF3IG/9t7WcyCuRJQOuTqrRerGk4a3pKcUUfhyc3Xk8NYeoE2LkOIjLEpcLHzOH8eBPxdXGCGQB2zMDaQLDA97V/yLTuLAZSs7w/YazEdxHay/vZMtmDU/Ht/Ob2tbz3uHKJPwF/8pf8SbcqvRrHyghVib3r8GS5fJY22wtO02aI8B7jls+llh1JdrMCZA7OMggt2jJeavXncNlG8esjMASzQMyWI6Z/ur+aiNgbzmqQkuuz3dt7WdzYzBA5L5VrlBFHpNLcCgzmm8mWMgZWeB4OPBpusEOaBqdZr6fnazb/cC7HQqA5aijRkxXUbV3YG4pCbpan0xBhwNGUG7y539WNQsIPj2p54=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
